services:
  - type: web
    name: wedding-app
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://mexeegqwlewmrsejdvlw.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_DSfOh1b64Rv6fX_J703Xzw_INxl1eMx
      - key: VITE_GOOGLE_DRIVE_FOLDER_ID
        value: 1VR9SeSoUy9_-1ylitBWOXZYtr3Z2DlYR
