import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { EditableCell } from './EditableCell';
import { Trash2, Plus } from 'lucide-react';
export function EditableTable({ columns, data, onUpdate, onDelete, onAdd, loading = false, title, }) {
    if (loading) {
        return (_jsx("div", { className: "flex justify-center items-center h-64", children: _jsx("div", { className: "text-gray-500", children: "Loading..." }) }));
    }
    return (_jsxs("div", { className: "w-full", children: [title && (_jsxs("div", { className: "flex justify-between items-center mb-4", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-800", children: title }), onAdd && (_jsxs("button", { onClick: onAdd, className: "flex items-center gap-2 px-4 py-2 bg-rose-gold hover:bg-rose-gold/90 text-white rounded-lg transition", children: [_jsx(Plus, { className: "w-4 h-4" }), "Add New"] }))] })), _jsx("div", { className: "overflow-x-auto rounded-lg border border-gray-200", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 border-b border-gray-200", children: _jsxs("tr", { children: [columns.map((col) => (_jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700", style: { width: col.width }, children: col.label }, col.key))), (onDelete || onAdd) && (_jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700 w-16", children: "Actions" }))] }) }), _jsx("tbody", { className: "divide-y divide-gray-200", children: data.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: columns.length + (onDelete ? 1 : 0), className: "px-4 py-8 text-center text-gray-500", children: "No records found" }) })) : (data.map((row, idx) => (_jsxs("tr", { className: "hover:bg-gray-50 transition", children: [columns.map((col) => (_jsx("td", { className: "px-4 py-3 text-sm text-gray-700", style: { width: col.width }, children: col.editable !== false ? (_jsx(EditableCell, { value: row[col.key], onSave: (value) => onUpdate(row.id, col.key, value), type: col.type, options: col.options })) : (_jsx("div", { className: "px-3 py-2", children: col.type === 'date'
                                                ? new Date(row[col.key]).toLocaleDateString()
                                                : String(row[col.key] || '') })) }, `${row.id}-${col.key}`))), onDelete && (_jsx("td", { className: "px-4 py-3 text-sm", children: _jsx("button", { onClick: () => onDelete(row.id), className: "text-red-600 hover:text-red-800 transition", children: _jsx(Trash2, { className: "w-4 h-4" }) }) }))] }, row.id || idx)))) })] }) })] }));
}
