import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { ChevronDown, Edit2, Trash2 } from 'lucide-react';
export default function GuestTable({ guests, onEdit, onDelete, onUpdateField, canEdit = () => true, canDelete = () => true, }) {
    const [sortBy, setSortBy] = useState('name');
    const [sortDesc, setSortDesc] = useState(false);
    const sortedGuests = [...guests].sort((a, b) => {
        let aVal = a[sortBy];
        let bVal = b[sortBy];
        if (sortBy === 'name') {
            return sortDesc
                ? bVal.localeCompare(aVal)
                : aVal.localeCompare(bVal);
        }
        return sortDesc ? bVal - aVal : aVal - bVal;
    });
    const totalPax = guests.reduce((sum, g) => sum + g.pax_total, 0);
    const confirmedPax = guests.reduce((sum, g) => (g.rsvp_status === 'Confirmed' ? sum + g.pax_total : sum), 0);
    const totalJain = guests.reduce((sum, g) => sum + g.jain_pax, 0);
    const confirmedGroups = guests.filter((g) => g.rsvp_status === 'Confirmed').length;
    const roomCount = guests.filter((g) => g.room_needed === 'Yes').length;
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "bg-gradient-to-r from-mauve/10 to-rose-gold/10 rounded-lg p-4 border border-mauve/20", children: _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-6 gap-4 text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Total Groups" }), _jsx("p", { className: "text-xl font-bold text-gray-800", children: guests.length })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Total Pax" }), _jsx("p", { className: "text-xl font-bold text-gray-800", children: totalPax })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Confirmed" }), _jsxs("p", { className: "text-xl font-bold text-green-700", children: [confirmedGroups, " / ", confirmedPax] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Jain Pax" }), _jsx("p", { className: "text-xl font-bold text-orange-700", children: totalJain })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Rooms Needed" }), _jsx("p", { className: "text-xl font-bold text-blue-700", children: roomCount })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-600 text-xs", children: "Avg Group Size" }), _jsx("p", { className: "text-xl font-bold text-gray-800", children: (totalPax / guests.length).toFixed(1) })] })] }) }), _jsx("div", { className: "overflow-x-auto border border-gray-200 rounded-lg", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-mauve/5 border-b border-gray-200", children: [_jsx("th", { className: "px-4 py-3 text-left font-semibold text-gray-700", children: "#" }), _jsx("th", { className: "px-4 py-3 text-left font-semibold text-gray-700 cursor-pointer hover:bg-mauve/10", onClick: () => {
                                            if (sortBy === 'name')
                                                setSortDesc(!sortDesc);
                                            setSortBy('name');
                                        }, children: _jsxs("div", { className: "flex items-center gap-1", children: ["Name ", _jsx(ChevronDown, { className: `w-4 h-4 ${sortBy === 'name' && sortDesc ? 'rotate-180' : ''}` })] }) }), _jsx("th", { className: "px-4 py-3 text-left font-semibold text-gray-700", children: "City" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700 cursor-pointer hover:bg-mauve/10", onClick: () => {
                                            if (sortBy === 'pax_total')
                                                setSortDesc(!sortDesc);
                                            setSortBy('pax_total');
                                        }, children: _jsxs("div", { className: "flex items-center justify-center gap-1", children: ["Pax ", _jsx(ChevronDown, { className: `w-4 h-4 ${sortBy === 'pax_total' && sortDesc ? 'rotate-180' : ''}` })] }) }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700 cursor-pointer hover:bg-mauve/10", onClick: () => {
                                            if (sortBy === 'side')
                                                setSortDesc(!sortDesc);
                                            setSortBy('side');
                                        }, children: _jsxs("div", { className: "flex items-center justify-center gap-1", children: ["Side ", _jsx(ChevronDown, { className: `w-4 h-4 ${sortBy === 'side' && sortDesc ? 'rotate-180' : ''}` })] }) }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "RSVP" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "Jain" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "F1" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "F2" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "F3" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "F4" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "Room" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "Hotel" }), _jsx("th", { className: "px-4 py-3 text-center font-semibold text-gray-700", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-200", children: sortedGuests.map((guest, idx) => (_jsxs("tr", { className: "hover:bg-gray-50 transition", children: [_jsx("td", { className: "px-4 py-3 text-gray-600", children: idx + 1 }), _jsx("td", { className: "px-4 py-3 font-medium text-gray-800", children: guest.name }), _jsx("td", { className: "px-4 py-3 text-gray-600 text-sm", children: guest.city }), _jsx("td", { className: "px-4 py-3 text-center font-medium text-gray-700", children: guest.pax_total }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsx("span", { className: `inline-block px-2 py-1 rounded text-xs font-semibold ${guest.side === 'Bride' ? 'bg-rose-gold/20 text-rose-gold' : 'bg-blue-100 text-blue-800'}`, children: guest.side }) }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsxs("select", { value: guest.rsvp_status, onChange: (e) => onUpdateField(guest.id, 'rsvp_status', e.target.value), className: `px-2 py-1 rounded text-xs font-semibold border-0 cursor-pointer ${guest.rsvp_status === 'Confirmed'
                                                ? 'status-confirmed'
                                                : guest.rsvp_status === 'Declined'
                                                    ? 'status-declined'
                                                    : 'status-undecided'}`, children: [_jsx("option", { value: "Confirmed", children: "Confirmed" }), _jsx("option", { value: "Not Decided", children: "Not Decided" }), _jsx("option", { value: "Declined", children: "Declined" })] }) }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsx("input", { type: "number", min: "0", max: guest.pax_total, value: guest.jain_pax, onChange: (e) => onUpdateField(guest.id, 'jain_pax', parseInt(e.target.value) || 0), className: "w-12 px-1 py-1 text-center border border-gray-300 rounded text-sm focus:ring-1 focus:ring-rose-gold focus:border-transparent" }) }), ['f1', 'f2', 'f3', 'f4'].map((fn) => (_jsx("td", { className: "px-4 py-3 text-center", children: _jsxs("select", { value: guest[fn], onChange: (e) => onUpdateField(guest.id, fn, e.target.value), className: `px-2 py-1 rounded text-xs font-semibold border-0 cursor-pointer ${guest[fn] === 'Yes'
                                                ? 'bg-green-100 text-green-800'
                                                : guest[fn] === 'No'
                                                    ? 'bg-red-100 text-red-800'
                                                    : 'status-tbd'}`, children: [_jsx("option", { value: "Yes", children: "Yes" }), _jsx("option", { value: "No", children: "No" }), _jsx("option", { value: "TBD", children: "TBD" })] }) }, fn))), _jsx("td", { className: "px-4 py-3 text-center", children: _jsxs("select", { value: guest.room_needed, onChange: (e) => onUpdateField(guest.id, 'room_needed', e.target.value), className: `px-2 py-1 rounded text-xs font-semibold border-0 cursor-pointer ${guest.room_needed === 'Yes'
                                                ? 'bg-blue-100 text-blue-800'
                                                : 'bg-gray-100 text-gray-800'}`, children: [_jsx("option", { value: "Yes", children: "Yes" }), _jsx("option", { value: "No", children: "No" })] }) }), _jsx("td", { className: "px-4 py-3 text-center text-xs", children: _jsxs("select", { value: guest.hotel_id || '', onChange: (e) => onUpdateField(guest.id, 'hotel_id', e.target.value || null), disabled: guest.room_needed === 'No', className: `px-1 py-1 rounded text-xs border border-gray-300 ${guest.room_needed === 'No' ? 'bg-gray-100 text-gray-500' : ''}`, children: [_jsx("option", { value: "", children: "Not Assigned" }), _jsx("option", { value: "leo-resort", children: "LEO Resort" }), _jsx("option", { value: "leo-medium", children: "LEO Medium" }), _jsx("option", { value: "xyz-hotel", children: "XYZ Hotel" }), _jsx("option", { value: "indralok", children: "Indralok" })] }) }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsxs("div", { className: "flex items-center justify-center gap-2", children: [canEdit(guest) && (_jsx("button", { onClick: () => onEdit(guest), className: "p-1 hover:bg-blue-100 rounded text-blue-600 transition", title: "Edit guest", children: _jsx(Edit2, { className: "w-4 h-4" }) })), canDelete(guest) && (_jsx("button", { onClick: () => onDelete(guest.id), className: "p-1 hover:bg-red-100 rounded text-red-600 transition", title: "Delete guest", children: _jsx(Trash2, { className: "w-4 h-4" }) })), !canEdit(guest) && !canDelete(guest) && (_jsx("span", { className: "text-xs text-gray-400", children: "View only" }))] }) })] }, guest.id))) })] }) })] }));
}
